name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IRONCLAD: ${{ secrets.IRONCLAD }}

    steps:
      - name: Cancel running workflows
        uses: everphone-gmbh/cancel-previous-workflows@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Prepare repository
        run: |
          git checkout -b dist origin/dist
          git merge main

      - name: Install dependencies
        run: |
          yarn install --production --pure-lockfile    

      - name: Build server and website
        run: |
          yarn build
          node prepareCI

      - name: Push from main to dist branch.
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Deploy ${{ github.sha }}'
          git push 
